---
title: "Homework12"
author: "Angela McMahon"
date: "4/21/2026"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(writexl)
library(dplyr)
library(ggplot2)
library(knitr)
```



```{r}
read_excel("penguins.xlsx")

t_island <- read_excel("penguins.xlsx", sheet="Torgersen Island", na="NA")
head(t_island)
b_island <- read_excel("penguins.xlsx", sheet="Biscoe Island", na="NA")
head(b_island)
d_island <- read_excel("penguins.xlsx", sheet="Dream Island", na="NA")
head(d_island)

```


```{r}
comb_islands <-bind_rows(T_Island, B_Island, D_Island)
head(comb_islands)
```


```{r}
ggplot(comb_islands, aes(x=bill_length_mm, y=bill_depth_mm, color=species))+
  geom_point()+
  facet_wrap(~island)
```


```{r}
comb_islands%>%
  group_by(species)%>%
  summarize(avg_weight=mean(body_mass_g, na.rm=TRUE))%>%
  kable()
```

```{r, class.source='fold-show'}
library(DBI)
library(duckdb)
con <- DBI::dbConnect(duckdb::duckdb())

```


```{r, class.source='fold-show'}
dbWriteTable(con, "comb_islands", comb_islands)
```


```{r}
comb_islands_db<-tbl(con,"comb_islands")
comb_islands_db%>%
  collect()
```


```{r}
comb_islands_db%>%
  select(species, body_mass_g)%>%
  group_by(species)%>%
  summarize(avg_mass=mean(body_mass_g, na.rm=TRUE))%>%
  show_query()
```

